"""
Pydantic schemas for the Conversations module.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from pydantic import BaseModel, Field, ConfigDict, field_validator
from app.modules.copilot.schemas import CitationSource


class ConversationCreate(BaseModel):
    """
    Schema representing a request to create a new conversation.
    """

    title: str | None = Field(
        default=None,
        description="The optional title of the conversation. Defaults to 'New Conversation'.",
        max_length=200,
    )


class ConversationResponse(BaseModel):
    """
    Schema representing a conversation session detail.
    """

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID = Field(
        ..., description="Unique UUID identifier for the conversation."
    )
    title: str = Field(
        ..., description="The title of the conversation session."
    )
    created_at: datetime = Field(
        ..., description="The timestamp when the conversation session was created."
    )
    updated_at: datetime = Field(
        ..., description="The timestamp when the conversation session was last updated."
    )


class MessageResponse(BaseModel):
    """
    Schema representing a single message payload in historical context.
    """

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID = Field(
        ..., description="Unique UUID identifier for the message."
    )
    conversation_id: uuid.UUID = Field(
        ..., description="The conversation ID to which the message belongs."
    )
    role: str = Field(
        ..., description="The sender's role: system, user, or assistant."
    )
    content: str = Field(
        ..., description="The text content of the message."
    )
    created_at: datetime = Field(
        ..., description="The timestamp when the message was sent."
    )


class ChatRequest(BaseModel):
    """
    Schema representing a multi-turn chat request submitted by a user.
    """

    conversation_id: uuid.UUID = Field(
        ..., description="The ID of the conversation session to continue."
    )
    message: str = Field(
        ...,
        description="The natural language message to send.",
        min_length=1,
        max_length=1000,
    )

    @field_validator("message")
    @classmethod
    def message_must_not_be_whitespace(cls, v: str) -> str:
        """Ensure the message is not just whitespace."""
        if not v.strip():
            raise ValueError("Message cannot be empty or whitespace only.")
        return v.strip()


class ChatResponse(BaseModel):
    """
    Schema representing the assistant's answer and explainability citations in a chat turn.
    """

    conversation_id: uuid.UUID = Field(
        ..., description="The conversation ID to which the turn belongs."
    )
    assistant_message: str = Field(
        ..., description="The answer generated by the assistant."
    )
    sources: list[CitationSource] = Field(
        ..., description="Citations used to compile and ground the answer."
    )
    confidence_score: float = Field(
        ..., description="The numerical confidence score of the answer (0.0 to 1.0)."
    )
    confidence_level: str = Field(
        ..., description="The categorized confidence level (HIGH, MEDIUM, LOW)."
    )
