"""create_documents_table

Revision ID: d6131442bcd9
Revises: 
Create Date: 2026-06-27 20:38:25.480052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6131442bcd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    
    # Enable PostgreSQL UUID generation extensions if available
    has_uuid_ossp = conn.execute(sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'uuid-ossp'")).scalar()
    if has_uuid_ossp:
        op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
        
    has_pgcrypto = conn.execute(sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'pgcrypto'")).scalar()
    if has_pgcrypto:
        op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')
    
    # Enable pgvector extension if available
    has_vector = conn.execute(sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'vector'")).scalar()
    if has_vector:
        op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('documents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('UNKNOWN', 'MANUAL', 'SOP', 'P_AND_ID', 'DRAWING', 'INSPECTION', 'REPORT', 'WORK_ORDER', 'OEM_MANUAL', name='document_type'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'PROCESSED', 'VALIDATING', 'STORED', 'READY', 'FAILED', name='document_status'), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
    
    # Drop enum types to ensure idempotency and clean rollback
    op.execute("DROP TYPE IF EXISTS document_status")
    op.execute("DROP TYPE IF EXISTS document_type")

