"""add_extraction_fields_to_documents

Revision ID: ef38e582cf95
Revises: e72c732f71de
Create Date: 2026-06-27 21:51:46.427246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef38e582cf95'
down_revision: Union[str, None] = 'e72c732f71de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        res = bind.execute(sa.text(
            "SELECT 1 FROM pg_type t "
            "JOIN pg_enum e ON t.oid = e.enumtypid "
            "WHERE t.typname = 'document_status' AND e.enumlabel = 'TEXT_EXTRACTED'"
        ))
        if not res.scalar():
            op.execute("ALTER TYPE document_status ADD VALUE 'TEXT_EXTRACTED'")

    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('extraction_method', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('extraction_language', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('extraction_confidence', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_at')
    op.drop_column('documents', 'extraction_confidence')
    op.drop_column('documents', 'extraction_language')
    op.drop_column('documents', 'extraction_method')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'extracted_text')
    # ### end Alembic commands ###
