"""
Pydantic schemas for the Copilot module.
"""

from __future__ import annotations

import uuid
from pydantic import BaseModel, Field, field_validator
from app.ai.retrieval import MAX_TOP_K


class CopilotQuestionRequest(BaseModel):
    """
    Schema representing a question request submitted to the Copilot.
    """

    question: str = Field(
        ...,
        description="The natural language question to ask the Copilot.",
        min_length=1,
        max_length=1000,
    )
    top_k: int = Field(
        default=5,
        description="The maximum number of context chunks to retrieve for grounding.",
        ge=1,
        le=MAX_TOP_K,
    )

    @field_validator("question")
    @classmethod
    def question_must_not_be_whitespace(cls, v: str) -> str:
        """Ensure the question is not just whitespace."""
        if not v.strip():
            raise ValueError("Question string cannot be empty or whitespace only.")
        return v.strip()


class CitationSource(BaseModel):
    """
    Schema representing a document chunk citation used to ground the answer.
    """

    filename: str = Field(
        ..., description="The name of the source document file."
    )
    document_id: uuid.UUID = Field(
        ..., description="The unique identifier of the source document."
    )
    chunk_id: uuid.UUID = Field(
        ..., description="The unique identifier of the matching chunk."
    )
    similarity_score: float = Field(
        ..., description="The vector similarity score for this chunk (0.0 to 1.0)."
    )
    page_number: int | None = Field(
        default=None, description="The estimated page number (represented by chunk_index)."
    )
    excerpt: str = Field(
        ..., description="A snippet/excerpt of the matching chunk."
    )


class RetrievalStatistics(BaseModel):
    """
    Schema representing diagnostic statistics about the RAG retrieval operation.
    """

    retrieved_chunks: int = Field(
        ..., description="The number of matching chunks retrieved."
    )
    average_similarity: float = Field(
        ..., description="The average vector similarity score across all retrieved chunks."
    )
    max_similarity: float = Field(
        ..., description="The maximum vector similarity score among all retrieved chunks."
    )
    processing_time_ms: float = Field(
        ..., description="The total retrieval execution time in milliseconds."
    )


class CopilotAnswerResponse(BaseModel):
    """
    Schema representing the answer response generated by the Copilot.
    """

    answer: str = Field(
        ..., description="The textual answer generated by the LLM."
    )
    confidence_score: float = Field(
        ..., description="The numerical confidence score of the answer (0.0 to 1.0)."
    )
    confidence_level: str = Field(
        ..., description="The categorized confidence level (HIGH, MEDIUM, LOW)."
    )
    sources: list[CitationSource] = Field(
        ..., description="The citations/sources used to compile and ground the answer."
    )
    supporting_chunks: list[str] = Field(
        ..., description="Highlighted excerpts from the retrieved chunks used to generate the answer."
    )
    retrieval_statistics: RetrievalStatistics = Field(
        ..., description="Retrieval performance metrics."
    )
